id: A49FD29F0
title: 'The Rain of Twofold Attainment: A Guru Yoga'
type: translation
pechas:
- IA8E88EB9
- I2E836F8B
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:13:38.040212
  last_modified_at: 2023-01-04 12:13:38.040228
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  IA8E88EB9/77A2: ECC9
  I2E836F8B/6846: ECC9
